site:
  title: CraftPG Docs
  start_page: craftpg::index.adoc
content:
  sources:
    - url: .
      start_path: .
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/raw/master/build/ui-bundle.zip
    snapshot: true
output:
  dir: build/site
