spring:
  application:
    name: 'Craftpg API'
    version: '@project.version@'
  profiles:
    active: '@activatedProfile@'
  datasource:
    url: jdbc:postgresql://${APP_DB_HOST}:${APP_DB_PORT}/${APP_DB_NAME}
    username: ${APP_DB_USER}
    password: ${APP_DB_PASS}
  mail:
    host: ${APP_MAIL_HOST}
    port: ${APP_MAIL_PORT}
    username: ${APP_MAIL_USER}
    password: ${APP_MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: ${APP_MAIL_SMTP_AUTH}
          starttls:
            enable: ${APP_MAIL_SMTP_STARTTLS}
  jpa:
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

app:
  keycloak:
    base-url: ${APP_KEYCLOAK_BASE_URL}
    admin:
      realm: ${APP_KEYCLOAK_ADMIN_REALM}
      client-id: ${APP_KEYCLOAK_ADMIN_CLIENT_ID}
      username: ${APP_KEYCLOAK_ADMIN_USERNAME}
      password: ${APP_KEYCLOAK_ADMIN_PASSWORD}
  invite:
    base-url: ${APP_INVITE_BASE_URL}
    mail-from: ${APP_INVITE_MAIL_FROM}
  minio:
    endpoint: ${MINIO_ENDPOINT}
    region: ${MINIO_REGION}
    bucket-maps: ${MINIO_BUCKET_MAPS}
    bucket-portraits: ${MINIO_BUCKET_PORTRAITS}
