spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/craftpg
    username: craftpg
    password: craftpg
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/craftpg

app:
  keycloak:
    base-url: http://localhost:8081
    admin:
      realm: master
      client-id: admin-cli
      username: admin
      password: admin
  invite:
    base-url: http://localhost:3000/invites
    mail-from: noreply@craftpg.local
  minio:
    endpoint: http://localhost:9000
    region: us-east-1
    bucket-maps: campaign-maps
    bucket-portraits: character-portraits
